#pragma once

//
// For Linux Compatibility
//
#ifndef CTL_CODE
#define FILE_ANY_ACCESS                 0
#define FILE_DEVICE_UNKNOWN             0x00000022
#define METHOD_NEITHER                  3
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)
#endif

//
// Root Bus IOCTLs
//
#define IOCTL_ADSS_CONTROL_DEVICE_CREATE_INSTANCE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1B, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// Bus Instance IOCTLs
//
#define IOCTL_ADSS_ENLIGHTENED_FORK                         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0F, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_ENLIGHTENED_FORK_CALLBACK                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x12, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_ENLIGHTENED_FORK_CALLBACK_STATUS         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x13, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_FILE_SYSTEM_CALLBACK                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x23, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_FILE_SYSTEM_CALLBACK_STATUS              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x24, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_ADSS_SET_INSTANCE_STATE                       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1C, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_MAP_PATH                             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1E, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_MAP_PATH_2                           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1F, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_UPDATE_NETWORK                           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x20, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_ADSS_CLIENT_OPEN                              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x21, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// Bus Client IOCTLs
//
#define IOCTL_ADSS_BUS_CLIENT_REGISTER_SERVER               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0A, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_CLIENT_CONNECT_SERVER                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0B, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef union _ADSS_BUS_CLIENT_CONNECT_SERVER_MSG
{
    struct
    {
        const char* ServerName;
        unsigned int Timeout;
        unsigned int Flags;
    };
    signed int ServerHandle;
} ADSS_BUS_CLIENT_CONNECT_SERVER_PARAMETERS, PADSS_BUS_CLIENT_CONNECT_SERVER_PARAMETERS;

//
// Server Port IOCTLs
//
#define IOCTL_ADSS_IPC_SERVER_WAIT_FOR_CONNECTION           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0C, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef union _ADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG
{
    unsigned int Timeout;
    unsigned int ClientHandle;
} ADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG, *PADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG;

//
// Message Port IOCTLs
//
#define IOCTL_ADSS_IPC_CONNECTION_SHARE_MEMORY              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0D, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNSHARE_MEMORY            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0E, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MAP_MEMORY                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x10, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMAP_MEMORY              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x11, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_CREATE_SHARED_SECTION     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x14, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_OPEN_SHARED_SECTION       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x15, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_REGISTER_SHARED_SECTION   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x16, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNREGISTER_SHARED_SECTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x07, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_REGISTER_SIGNAL_EVENT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x18, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_SET_SIGNAL_EVENT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x19, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_PID               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x25, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_PID             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x26, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_HANDLE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x27, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_HANDLE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x28, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_CONSOLE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x29, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_CONSOLE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2A, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_FORK_TOKEN        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2B, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_FORK_TOKEN      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2C, METHOD_NEITHER, FILE_ANY_ACCESS)
