#pragma once
#pragma warning(push)
#pragma warning(disable:4201)

//
// For Linux Compatibility
//
#ifndef CTL_CODE
#define FILE_ANY_ACCESS                 0
#define FILE_DEVICE_UNKNOWN             0x00000022
#define METHOD_NEITHER                  3
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)
#endif

//
// Root Bus IOCTLs
//
#define IOCTL_ADSS_CONTROL_DEVICE_CREATE_INSTANCE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1B, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// Bus Instance IOCTLs
//
#define IOCTL_ADSS_ENLIGHTENED_FORK                         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0F, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_ENLIGHTENED_FORK_CALLBACK                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x12, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_ENLIGHTENED_FORK_CALLBACK_STATUS         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x13, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_FILE_SYSTEM_CALLBACK                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x23, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_FILE_SYSTEM_CALLBACK_STATUS              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x24, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_ADSS_SET_INSTANCE_STATE                       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1C, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_MAP_PATH                             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1E, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_MAP_PATH_2                           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1F, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_UPDATE_NETWORK                           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x20, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_ADSS_CLIENT_OPEN                              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x21, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// Bus Client IOCTLs
//
#define IOCTL_ADSS_BUS_CLIENT_REGISTER_SERVER               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0A, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_BUS_CLIENT_CONNECT_SERVER                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0B, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ADSS_CONNECT_WAIT_FOR_SERVER_FLAG 0x01
#define ADSS_CONNECT_UNNAMED_SERVER_FLAG  0x02
typedef union _ADSS_BUS_CLIENT_CONNECT_SERVER_MSG
{
    struct
    {
        const char* ServerName;
        unsigned int Timeout;
        unsigned int Flags;
    };
    signed int ServerHandle;
} ADSS_BUS_CLIENT_CONNECT_SERVER_MSG, PADSS_BUS_CLIENT_CONNECT_SERVER_MSG;

//
// Server Port IOCTLs
//
#define IOCTL_ADSS_IPC_SERVER_WAIT_FOR_CONNECTION           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0C, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef union _ADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG
{
    unsigned int Timeout;
    unsigned int ClientHandle;
} ADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG, *PADSS_IPC_SERVER_WAIT_FOR_CONNECTION_MSG;

//
// Message Port IOCTLs
//
#define IOCTL_ADSS_IPC_CONNECTION_SHARE_MEMORY              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0D, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNSHARE_MEMORY            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0E, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MAP_MEMORY                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x10, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMAP_MEMORY              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x11, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_CREATE_SHARED_SECTION     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x14, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_OPEN_SHARED_SECTION       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x15, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_REGISTER_SHARED_SECTION   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x16, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNREGISTER_SHARED_SECTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x07, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_REGISTER_SIGNAL_EVENT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x18, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_SET_SIGNAL_EVENT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x19, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_CLEAR_SIGNAL_EVENT        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1A, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_PID               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x25, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_PID             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x26, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_HANDLE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x27, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef enum _ADSS_IPC_CONNECTION_MARSHAL_HANDLE_TYPE
{
    ConsoleHandleType,
    LxInputPipeType,
    LxOutputPipeType,
    NtInputPipeType,
    NtOutputPipeType
} ADSS_IPC_CONNECTION_MARSHAL_HANDLE_TYPE;
typedef union _ADSS_IPC_CONNECTION_MARSHAL_HANDLE_MSG
{
    struct
    {
        unsigned int Handle;
        ADSS_IPC_CONNECTION_MARSHAL_HANDLE_TYPE Type;
    };
    unsigned long long HandleId;
} ADSS_IPC_CONNECTION_MARSHAL_HANDLE_MSG;
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_HANDLE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x28, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_CONSOLE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x29, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_CONSOLE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2A, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_FORK_TOKEN        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2B, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef union _ADSS_IPC_CONNECTION_MARSHAL_FORK_TOKEN_MSG
{
    unsigned int TokenHandle;
    unsigned long long TokenId;
} ADSS_IPC_CONNECTION_MARSHAL_FORK_TOKEN_MSG, *PADSS_IPC_CONNECTION_MARSHAL_FORK_TOKEN_MSG;
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_FORK_TOKEN      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2C, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_MARSHAL_VFS_FILE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2D, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_VFS_FILE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2E, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_CREATE_UNNAMED_SERVER     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x30, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_UNMARSHAL_SERVER_PORT     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x31, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_RELEASE_HANDLES           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x32, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_ADSS_IPC_CONNECTION_DISCONNECT_CONSOLE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x33, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// VFS NT File IOCTLs
//
#define IOCTL_ADSS_NT_PROCESS_FILE_WAIT_FOR_SIGNAL          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2F, METHOD_NEITHER, FILE_ANY_ACCESS)

//
// LX Process Handle IOCTLs
//
typedef struct _ADSS_LX_PROCESS_HANDLE_WAIT_FOR_SIGNAL_MSG
{
    unsigned int ExitStatus;
} ADSS_LX_PROCESS_HANDLE_WAIT_FOR_SIGNAL_MSG, *PADSS_LX_PROCESS_HANDLE_WAIT_FOR_SIGNAL_MSG;
#define IOCTL_ADSS_LX_PROCESS_HANDLE_WAIT_FOR_SIGNAL        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x34, METHOD_NEITHER, FILE_ANY_ACCESS)
typedef struct _ADSS_LX_PROCESS_HANDLE_GET_NT_PID_MSG
{
    unsigned int NtPid;
} ADSS_LX_PROCESS_HANDLE_GET_NT_PID_MSG, *PADSS_LX_PROCESS_HANDLE_GET_NT_PID_MSG;
#define IOCTL_ADSS_LX_PROCESS_HANDLE_GET_NT_PID             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x35, METHOD_NEITHER, FILE_ANY_ACCESS)


#pragma warning(pop)
